name: Actions Workflow

on: 
  #push:
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/10 * * * *"
  pull_request:
    types: [closed, assigned,opened, reopened]

jobs: 
  run-gihub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1 
      - name: List files  After
        run: |
          pwd
          ls -a  
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Adesh
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"